// <auto-generated />
using System;
using ClimaTempo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClimaTempo.Migrations
{
    [DbContext(typeof(ClimaTempoSimplesContext))]
    [Migration("20220912104058_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClimaTempo.Models.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 2,
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 2,
                            Nome = "Campinas"
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 1,
                            Nome = "Barra Mansa"
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 1,
                            Nome = "Volta Redonda"
                        });
                });

            modelBuilder.Entity("ClimaTempo.Models.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Rio de Jaineiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "São Paulo",
                            UF = "SP"
                        });
                });

            modelBuilder.Entity("ClimaTempo.Models.Entities.PrevisaoClima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Clima")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TemperaturaMaxima")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TemperaturaMinima")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("PrevisoesClima");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadeId = 1,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 12, 7, 40, 57, 637, DateTimeKind.Local).AddTicks(3198),
                            TemperaturaMaxima = 34m,
                            TemperaturaMinima = 24m
                        },
                        new
                        {
                            Id = 2,
                            CidadeId = 1,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 13, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(505),
                            TemperaturaMaxima = 30m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 3,
                            CidadeId = 1,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 14, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(562),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 16m
                        },
                        new
                        {
                            Id = 4,
                            CidadeId = 1,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 15, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(571),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 5,
                            CidadeId = 1,
                            Clima = 2,
                            DataPrevisao = new DateTime(2022, 9, 16, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(576),
                            TemperaturaMaxima = 24m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 6,
                            CidadeId = 1,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 17, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(580),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 15m
                        },
                        new
                        {
                            Id = 7,
                            CidadeId = 1,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 18, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(584),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 8,
                            CidadeId = 2,
                            Clima = 2,
                            DataPrevisao = new DateTime(2022, 9, 12, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(589),
                            TemperaturaMaxima = 32m,
                            TemperaturaMinima = 22m
                        },
                        new
                        {
                            Id = 9,
                            CidadeId = 2,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 13, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(597),
                            TemperaturaMaxima = 33m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 10,
                            CidadeId = 2,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 14, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(602),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 16m
                        },
                        new
                        {
                            Id = 11,
                            CidadeId = 2,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 15, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(605),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 12,
                            CidadeId = 2,
                            Clima = 2,
                            DataPrevisao = new DateTime(2022, 9, 16, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(609),
                            TemperaturaMaxima = 23m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 13,
                            CidadeId = 2,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 17, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(613),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 15m
                        },
                        new
                        {
                            Id = 14,
                            CidadeId = 2,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 18, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(618),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 15,
                            CidadeId = 3,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 12, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(622),
                            TemperaturaMaxima = 30m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 16,
                            CidadeId = 3,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 13, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(629),
                            TemperaturaMaxima = 30m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 17,
                            CidadeId = 3,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 14, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(635),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 16m
                        },
                        new
                        {
                            Id = 18,
                            CidadeId = 3,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 15, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(639),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 19,
                            CidadeId = 3,
                            Clima = 2,
                            DataPrevisao = new DateTime(2022, 9, 16, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(642),
                            TemperaturaMaxima = 24m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 20,
                            CidadeId = 3,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 17, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(646),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 15m
                        },
                        new
                        {
                            Id = 21,
                            CidadeId = 3,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 18, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(649),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 22,
                            CidadeId = 4,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 12, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(652),
                            TemperaturaMaxima = 28m,
                            TemperaturaMinima = 18m
                        },
                        new
                        {
                            Id = 23,
                            CidadeId = 4,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 13, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(656),
                            TemperaturaMaxima = 30m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 24,
                            CidadeId = 4,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 14, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(660),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 16m
                        },
                        new
                        {
                            Id = 25,
                            CidadeId = 4,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 15, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(663),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 26,
                            CidadeId = 4,
                            Clima = 2,
                            DataPrevisao = new DateTime(2022, 9, 16, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(667),
                            TemperaturaMaxima = 24m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 27,
                            CidadeId = 4,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 17, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(671),
                            TemperaturaMaxima = 25m,
                            TemperaturaMinima = 15m
                        },
                        new
                        {
                            Id = 28,
                            CidadeId = 4,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 18, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(674),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 20m
                        },
                        new
                        {
                            Id = 29,
                            CidadeId = 5,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 12, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(678),
                            TemperaturaMaxima = 26m,
                            TemperaturaMinima = 16m
                        },
                        new
                        {
                            Id = 30,
                            CidadeId = 5,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 13, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(681),
                            TemperaturaMaxima = 30m,
                            TemperaturaMinima = 22m
                        },
                        new
                        {
                            Id = 31,
                            CidadeId = 5,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 14, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(684),
                            TemperaturaMaxima = 27m,
                            TemperaturaMinima = 18m
                        },
                        new
                        {
                            Id = 32,
                            CidadeId = 5,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 15, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(688),
                            TemperaturaMaxima = 22m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 33,
                            CidadeId = 5,
                            Clima = 0,
                            DataPrevisao = new DateTime(2022, 9, 16, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(691),
                            TemperaturaMaxima = 21m,
                            TemperaturaMinima = 13m
                        },
                        new
                        {
                            Id = 34,
                            CidadeId = 5,
                            Clima = 3,
                            DataPrevisao = new DateTime(2022, 9, 17, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(694),
                            TemperaturaMaxima = 22m,
                            TemperaturaMinima = 14m
                        },
                        new
                        {
                            Id = 35,
                            CidadeId = 5,
                            Clima = 1,
                            DataPrevisao = new DateTime(2022, 9, 18, 7, 40, 57, 639, DateTimeKind.Local).AddTicks(698),
                            TemperaturaMaxima = 24m,
                            TemperaturaMinima = 19m
                        });
                });

            modelBuilder.Entity("ClimaTempo.Models.Entities.Cidade", b =>
                {
                    b.HasOne("ClimaTempo.Models.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("ClimaTempo.Models.Entities.PrevisaoClima", b =>
                {
                    b.HasOne("ClimaTempo.Models.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });
#pragma warning restore 612, 618
        }
    }
}
